In [16]:
#1
import numpy as np
ar1 = np.pad(np.zeros((8,8), int), 1, constant_values=1)
print(ar1)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [14]:
#2
ar2 = (np.arange(8)[:, None] + np.arange(8)) % 2
print(ar2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#3
ar3 = np.transpose(np.eye(5, k=1)*1 + np.eye(5, k=2)*2 + np.eye(5, k=3)*3 + np.eye(5, k=4)*4)
print(ar3)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]]


In [23]:
#4
ar4 = (lambda a: a - a.mean(axis=1, keepdims=True))(np.random.rand(5,5))
print(ar4.mean(axis=1))
print(np.allclose(ar4.mean(axis=1), 0))

[ 1.11022302e-16  2.22044605e-17 -4.44089210e-17 -2.22044605e-17
  4.44089210e-17]
True


In [25]:
#5
ar5 = np.random.rand(10,3)
closest = ar5[np.arange(10), np.abs(ar5-0.5).argmin(axis=1)]
print(ar5)
print(closest)

[[0.75920599 0.48747549 0.56198836]
 [0.88984444 0.00453138 0.78953307]
 [0.70085294 0.62961676 0.43417267]
 [0.10340265 0.85190481 0.89096606]
 [0.96603019 0.64268661 0.22946189]
 [0.33114512 0.31164294 0.60242018]
 [0.07723749 0.53522031 0.49045167]
 [0.62831768 0.69051372 0.30795004]
 [0.8723443  0.6165302  0.89706732]
 [0.09875263 0.75159873 0.59754277]]
[0.48747549 0.78953307 0.43417267 0.85190481 0.64268661 0.60242018
 0.49045167 0.62831768 0.6165302  0.59754277]


In [26]:
# 6
ar6 = np.random.rand(6,6)
res6 = ar6.sum(axis=1) / ar6.max(axis=0)
print(ar6)
print(res6)

[[0.40679435 0.73265789 0.15140271 0.22060884 0.43746944 0.74809314]
 [0.99867945 0.74586865 0.07335182 0.69599281 0.74841543 0.96632917]
 [0.81408071 0.23880202 0.19143513 0.94715834 0.13206163 0.23221959]
 [0.12275693 0.1579891  0.80219072 0.85995451 0.34617899 0.73262123]
 [0.97271775 0.07769983 0.54893971 0.83412589 0.86536714 0.79597529]
 [0.13294759 0.66408959 0.40239962 0.17174711 0.04166828 0.83525002]]
[2.70059263 5.66941287 3.18597229 3.19027068 4.73189405 2.32643522]


In [27]:
# 7
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
res7 = x[1:][x[:-1]==0].max()
print(res7)

5


In [28]:
# 8
x = np.ones(10, dtype=int)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength=len(x))
print(x)

[2 2 2 2 1 4 1 1 2 1]


In [29]:
# 9
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])
res9 = b[np.abs(a[...,None]-b).argmin(axis=-1)]
print(res9)

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


In [31]:
# 10
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])
b = np.convolve(a, np.ones(3)/3, mode='valid')
print(b)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
